<?xml version="1.0"?>

<!DOCTYPE gares-fret [
<!ELEMENT gares-fret (gare)+>

<!ELEMENT gare (libelle,plateforme)>
<!ATTLIST gare code CDATA #REQUIRED>

<!ELEMENT libelle (#PCDATA)>

<!ELEMENT plateforme (code-gare)>
<!ATTLIST plateforme code NMTOKEN #REQUIRED>

<!ELEMENT code-gare (#PCDATA)>
]>


<gares>
<gare code="672212">
  <libelle>ARTIX</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="673004">
  <libelle>BAYONNE</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="673012">
  <libelle>BAYONNE-ALLEES-MARINES</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="673095">
  <libelle>BOUCAU</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="672220">
  <libelle>LACQ</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="673103">
  <libelle>MORCENX SC</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="672006">
  <libelle>PAU SC</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="679324">
  <libelle>TARTAS SC</libelle>
  <plateforme code="BYE">
    <code-gare>673004</code-gare>
  </plateforme>
</gare>
<gare code="313874">
  <libelle>AMIENS SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="296327">
  <libelle>ATHIES-SOUS-LAON SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="171462">
  <libelle>BAZANCOURT</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="118752">
  <libelle>BRIENNE-LE-CHATEAU</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="174003">
  <libelle>CHALONS-EN-CHAMPAGNE</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="172007">
  <libelle>CHARLEVILLES MEZIERES SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="296616">
  <libelle>CHAUNY SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="296152">
  <libelle>CREPY-COUVRON SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="315119">
  <libelle>CROIX-SAVOYARD-GARAGE(LA) SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="171371">
  <libelle>FERE-EN-TARDENOIS</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="296012">
  <libelle>LAON SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="313049">
  <libelle>LONGUEAU SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="172197">
  <libelle>LUMES TRIAGE SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="174573">
  <libelle>MAILLY-LE-CAMP SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="296095">
  <libelle>MARLE-SUR-SERRE SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="116103">
  <libelle>MEAUX</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="313197">
  <libelle>MONTIERES (QUARTIER-D&apos;AMIENS) SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="174409">
  <libelle>MOURMELON-LE-PETIT SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="313486">
  <libelle>NESLE (SOMME) SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="296467">
  <libelle>ORIGNY-STE-BENOITE SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="171280">
  <libelle>ST BRICE-COURCELLES</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="171751">
  <libelle>ST ERME SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="174441">
  <libelle>ST HILAIRE-AU-TEMPLE SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="174821">
  <libelle>SUIPPES SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="276741">
  <libelle>THOUROTTE</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="118000">
  <libelle>TROYES</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="172114">
  <libelle>VIREUX MOLHAIN SC</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="174219">
  <libelle>VITRY-LA-VILLE</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="174276">
  <libelle>VITRY-LE-FRANCOIS</libelle>
  <plateforme code="CM">
    <code-gare>174003</code-gare>
  </plateforme>
</gare>
<gare code="281402">
  <libelle>COUDEKERQUE-BRANCHE</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="317149">
  <libelle>DESVRES</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="281006">
  <libelle>DUNKERQUE LOCAL</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="287037">
  <libelle>DUNKERQUE-GRANDE-SYNTHE</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="281204">
  <libelle>DUNKERQUE-PORT-EST</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="577981">
  <libelle>DUNKERQUE-PORT-EST RECYCL</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="281030">
  <libelle>DUNKERQUE-PORT-OUEST</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="241240">
  <libelle>DUNKERQUE-ZONE-PONDEREUX</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="281626">
  <libelle>LEFFRINCKOUCKE</libelle>
  <plateforme code="DKQ">
    <code-gare>287037</code-gare>
  </plateforme>
</gare>
<gare code="718007">
  <libelle>BESANCON</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="142026">
  <libelle>BRICON SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="725002">
  <libelle>CHALON-SUR-SAONE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="694000">
  <libelle>CREUSOT (LE)</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="725028">
  <libelle>CRISSEY-GARAGE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="142125">
  <libelle>CULMONT-CHALINDREY SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="694695">
  <libelle>DIGOIN</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713867">
  <libelle>DIJON-PTE-D OUCHE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713008">
  <libelle>DIJON-PTE-NEUVE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713412">
  <libelle>DOLE-VILLE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="718304">
  <libelle>FRANOIS</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713032">
  <libelle>GEVREY-TRIAGE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713859">
  <libelle>IS-SUR-TILLE SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="683243">
  <libelle>JOIGNY SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="175091">
  <libelle>JOINVILLE (HAUTE-MARNE) SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="142091">
  <libelle>LANGRES SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="683268">
  <libelle>LAROCHE-MIGENNES SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713115">
  <libelle>LAUMES-ALESIA (LES) SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="729111">
  <libelle>MACON (PORT-FLUVIAL)</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713131">
  <libelle>MONTBARD</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="694307">
  <libelle>MONTCHANIN</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="694687">
  <libelle>PARAY-LE-MONIAL SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713875">
  <libelle>PERRIGNY-TRIAGE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="725614">
  <libelle>SENNECEY-LE-GRAND</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713677">
  <libelle>SEURRE SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="577890">
  <libelle>SEURRE ATELIER SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="142562">
  <libelle>STE-COLOMBE-SUR-SEINE</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="713487">
  <libelle>TAVAUX-SOLVAY</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="718544">
  <libelle>VALDAHON(LE) SC</libelle>
  <plateforme code="GEV">
    <code-gare>713032</code-gare>
  </plateforme>
</gare>
<gare code="413484">
  <libelle>GRAVENCHON-PORT-JEROME</libelle>
  <plateforme code="HAV">
    <code-gare>413013</code-gare>
  </plateforme>
</gare>
<gare code="413013">
  <libelle>HAVRE (LE)</libelle>
  <plateforme code="HAV">
    <code-gare>413013</code-gare>
  </plateforme>
</gare>
<gare code="581868">
  <libelle>BASSENS-APPONTEMENTS</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="581884">
  <libelle>BEC-D&apos;AMBES (LE)</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="584268">
  <libelle>BERGERAC SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="586164">
  <libelle>BON-ENCONTRE SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="581827">
  <libelle>BORDEAUX-HOURCADE</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="581009">
  <libelle>BORDEAUX-ST-JEAN</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="581736">
  <libelle>BRUGES SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="581876">
  <libelle>CHAPELLE-D&apos;AMBES (LA)</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="582551">
  <libelle>LABOUHEYRE SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="673129">
  <libelle>LALUQUE SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="595298">
  <libelle>MUSSIDAN SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="595009">
  <libelle>PERIGUEUX SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="491209">
  <libelle>ST MARIENS-ST-YZAN (NUCLEAIRE) SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="582643">
  <libelle>TESTE (LA) SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="584714">
  <libelle>VAYRES SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="582536">
  <libelle>YCHOUX (ARMEES) SC</libelle>
  <plateforme code="HDE">
    <code-gare>581827</code-gare>
  </plateforme>
</gare>
<gare code="214593">
  <libelle>GRESSWILLER SC</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212092">
  <libelle>HAUSBERGEN-TRIAGE</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212340">
  <libelle>HERRLISHEIM (BAS-RHIN)</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212316">
  <libelle>LA WANTZENAU</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212464">
  <libelle>LAUTERBOURG SC</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212720">
  <libelle>OBERHOFFEN-CAMP-HAGUENAU(ARMEE SC</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="213231">
  <libelle>REICHSHOFFEN-USINES</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212381">
  <libelle>REICHSTETT-GARAGE</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="577973">
  <libelle>STRASBOURG PORT DU RHIN RECYCL</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212050">
  <libelle>STRASBOURG-CRONENBOURG</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212068">
  <libelle>STRASBOURG-NEUDORF</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212076">
  <libelle>STRASBOURG-PORT-DU-RHIN</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="212027">
  <libelle>STRASBOURG-VILLE (SERVICES)</libelle>
  <plateforme code="HSG">
    <code-gare>212092</code-gare>
  </plateforme>
</gare>
<gare code="677005">
  <libelle>HENDAYE</libelle>
  <plateforme code="HYE">
    <code-gare>677005</code-gare>
  </plateforme>
</gare>
<gare code="386466">
  <libelle>ACHERES</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="583005">
  <libelle>ANGOULEME SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="543017">
  <libelle>AUBRAIS (LES) SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="315168">
  <libelle>AVRIGNY</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="485169">
  <libelle>AYTRE SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="315341">
  <libelle>BAILLEUL-SUR-THERAIN-GARAGE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="271478">
  <libelle>BLANC-MESNIL (LE)</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="415893">
  <libelle>BONNIERES</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="576207">
  <libelle>BOURGES SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="271395">
  <libelle>BOURGET (LE)</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="271312">
  <libelle>BOURGET-TRIAGE (LE)</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="545194">
  <libelle>BRETIGNY SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="543348">
  <libelle>BRICY-BOULAY SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="484659">
  <libelle>CHATEAU-GONTIER SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="543462">
  <libelle>CHATEAUNEUF-SUR-LOIRE SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="597005">
  <libelle>CHATEAUROUX SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="118133">
  <libelle>CHATRES SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="276691">
  <libelle>COMPIEGNE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="276006">
  <libelle>CREIL</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="276147">
  <libelle>EPLUCHES</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="543124">
  <libelle>FERTE-ST-AUBIN (LA) SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="386011">
  <libelle>FOLIE-NANTERRE (LA)</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="381566">
  <libelle>GARGENVILLE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="271205">
  <libelle>GENNEVILLIERS</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="684290">
  <libelle>GIEN SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="115881">
  <libelle>GRANDPUITS</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="112086">
  <libelle>GRANDPUITS-BAGNEUX</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="575134">
  <libelle>INGRANDES-SUR-VIENNE SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="276873">
  <libelle>LAMOTTE-BREUIL</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="575845">
  <libelle>LUSSAC-LES-CHATEAUX SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="681163">
  <libelle>MAISONS-ALFORT-POMPADOUR</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="396002">
  <libelle>MANS (LE) SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="381509">
  <libelle>MANTES-LA-JOLIE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="116590">
  <libelle>MEZY</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="684563">
  <libelle>MIGNERES GONDREVILLE SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="271528">
  <libelle>MITRY-CLAYE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="574681">
  <libelle>MONNAIE SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="682302">
  <libelle>MONTEREAU</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="276477">
  <libelle>MOULIN-NEUF-GARAGE (OISE) SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="386680">
  <libelle>MUREAUX (LES)</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="116095">
  <libelle>NANGIS</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="597070">
  <libelle>NEUVY-PAILLOUX SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="118190">
  <libelle>NOGENT SUR SEINE SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="577866">
  <libelle>NOISY LE SC CMT ATELIER SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="113225">
  <libelle>NOISY-LE-SEC-MULTITECHNIQUE SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="276782">
  <libelle>NOYON SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="214312">
  <libelle>OBERNAI-BRASSERIE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="113209">
  <libelle>PANTIN</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="545053">
  <libelle>PARIS-AUSTERLITZ (PARIS-TOLBIAC)</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="545004">
  <libelle>PARIS-TOLBIAC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="113134">
  <libelle>PARIS-VILLETTE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="276469">
  <libelle>PERSAN-BEAUMONT</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="386573">
  <libelle>POISSY</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="575001">
  <libelle>POITIERS SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="571794">
  <libelle>PORT-BOULET SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="114421">
  <libelle>PORT-DE-BONNEUIL</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="681338">
  <libelle>RIS-ORANGIS</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="485011">
  <libelle>ROCHELLE-PALLICE (LA) SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="485003">
  <libelle>ROCHELLE-VILLE (LA) SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="491001">
  <libelle>SAINTES SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="543165">
  <libelle>SALBRIS SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="576322">
  <libelle>ST AMAND-MONTROND SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="393223">
  <libelle>ST CYR SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="543116">
  <libelle>ST CYR-EN-VAL SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="543439">
  <libelle>ST DENIS-JARGEAU SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="271221">
  <libelle>ST OUEN-LES-DOCKS</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="571240">
  <libelle>ST PIERRE-DES-CORPS SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="114413">
  <libelle>SUCY-BONNEUIL (SAUF PORT)</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="487009">
  <libelle>THOUARS SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="571000">
  <libelle>TOURS SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="116293">
  <libelle>VAIRES-TORCY</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="271387">
  <libelle>VALENTON</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="577916">
  <libelle>VALENTON ATELIER</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="386656">
  <libelle>VERNOUILLET-VERNEUIL SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="393132">
  <libelle>VERSAILLES-MATELOTS SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="576009">
  <libelle>VIERZON SC</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="681809">
  <libelle>VILLENEUVE-ST-GEORGES-TRIAGE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="545277">
  <libelle>VILLENEUVE LE ROI</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="545293">
  <libelle>VITRY-SUR-SEINE</libelle>
  <plateforme code="IDF">
    <code-gare>271395</code-gare>
  </plateforme>
</gare>
<gare code="755447">
  <libelle>ARCS (LES) SC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="764613">
  <libelle>ARDOISE (L&apos;) SC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753657">
  <libelle>ARLES SC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="765008">
  <libelle>AVIGNON</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="765024">
  <libelle>AVIGNON-FONTCOUVERTE</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="759241">
  <libelle>BEL-AIR-LA-MEDE</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753228">
  <libelle>BERRE</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="757005">
  <libelle>CANNES-MARCHANDISES SC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="751776">
  <libelle>CASSIS SC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="751230">
  <libelle>CHATEAU-ARNOUX-ST-AUBAN</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753186">
  <libelle>ENTRESSEN SC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753434">
  <libelle>FOS-COUSSOUL</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="578104">
  <libelle>FOS-COUSSOUL ATELIER</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753467">
  <libelle>FOS-GRAVELEAU</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753475">
  <libelle>FOS-MERIQUETTE</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753483">
  <libelle>FOS-MOLE-CENTRAL</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="775791">
  <libelle>GENERAC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="751081">
  <libelle>MARSEILLE-BLANCARDE</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753509">
  <libelle>MARTIGUES</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="753004">
  <libelle>MIRAMAS</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="577833">
  <libelle>MIRAMAS ATELIER</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="755835">
  <libelle>MOTTE-STE-ROSSELINE (LA) SC</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>
<gare code="775007">
  <libelle>NÎMES</libelle>
  <plateforme code="MAS">
    <code-gare>753004</code-gare>
  </plateforme>
</gare>